[package]
name = "glyn_unicode"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "generate_unicode"
path = "bin/generate_unicode.rs"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
regex = "1.10"
