[package]
name = "glyn_interpreter"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glyn_unicode = { workspace = true }

[[bin]]
name = "cli"
path = "src/bin/cli.rs"

[features]
debug = []
