[package]
name = "glyn_interpreter"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glyn_unicode = { workspace = true }
safe-gc = "1.1.1"

[[bin]]
name = "eval_script"
path = "src/bin/eval_script.rs"
